// A base do "Tire sua dúvida": as perguntas sobre COMO USAR o sistema, cada uma
// com vários jeitos de perguntar (termos) e a resposta em passos curtos.
// Nada clínico aqui — mesma regra do resto do app.
//
// É aqui que se ensina a busca (js/busca.js não sabe nada do fluxograma):
// dúvida nova, ou pergunta que caiu na resposta errada → acrescente frases
// nos termos (frases com duas palavras de conteúdo valem mais que palavra
// solta) e um caso em testes/duvidas.test.js.
//
// mostrar: seletor do que pisca em "Mostrar na tela" (tem de existir no index.html).

export const BASE = [
  {
    id: 'usar-geral',
    pergunta: 'Como usar o sistema, do começo ao fim?',
    termos: ['como usar', 'como funciona', 'como funciona isso', 'passo a passo', 'por onde comeco', 'por onde começar',
      'como comecar', 'nao sei usar', 'nao sei mexer', 'primeira vez', 'tutorial', 'manual', 'ajuda', 'me ensina',
      'explicar como funciona', 'o que faco primeiro', 'primeiro passo'],
    passos: [
      'Escolha "Começar com o modelo" (as formas já vêm no lugar) ou "Começar com a folha vazia".',
      'Para escrever, clique numa forma e digite. Para terminar, clique fora dela.',
      'Para mover, aperte o botão do mouse em cima da forma e arraste.',
      'Para pôr uma forma nova, use os botões da esquerda (Retângulo, Losango...).',
      'Para ligar formas, clique numa forma e depois no + azul. Ou use o botão Seta.',
      'Errou? Clique em Desfazer. Terminou? Clique em "Imprimir ou PDF".',
      'Para continuar outro dia, use "Salvar no computador" e, depois, Abrir.',
    ],
    comum: true,
  },
  {
    id: 'escrever',
    pergunta: 'Como escrever dentro de uma forma?',
    termos: ['escrever', 'escrevo', 'digitar', 'digito', 'colocar texto', 'botar texto', 'escrever na caixa',
      'escrever no quadrado', 'escrever na forma', 'onde escrevo', 'onde digito', 'preencher', 'colocar palavra',
      'colocar o nome', 'texto na forma', 'nao consigo escrever', 'nao aparece o que eu digito', 'nao escreve'],
    passos: [
      'Clique uma vez na forma.',
      'Quando aparecer o risquinho piscando, é só digitar.',
      'Para terminar, clique fora da forma.',
    ],
    mostrar: '#folha',
    comum: true,
  },
  {
    id: 'apagar-texto',
    pergunta: 'Como apagar ou corrigir o que escrevi?',
    termos: ['apagar o que escrevi', 'apagar texto', 'apagar o texto', 'apagar a palavra', 'apagar letra', 'corrigir',
      'corrijo', 'corrigir o texto', 'escrevi errado', 'errei a palavra', 'errei o texto', 'mudar o texto',
      'trocar o texto', 'editar o texto', 'arrumar o texto', 'consertar o texto'],
    passos: [
      'Clique na forma, no ponto do texto que quer mudar.',
      'Use a tecla de apagar (Backspace, a tecla grande com a seta ←) ou a tecla Delete.',
      'Ou passe o mouse por cima das palavras, com o botão apertado, e digite por cima.',
    ],
  },
  {
    id: 'mover',
    pergunta: 'Como mudar uma forma de lugar?',
    termos: ['mover', 'mexer a caixa', 'arrastar', 'arrasto', 'mudar de lugar', 'trocar de lugar', 'levar para outro lugar',
      'empurrar', 'puxar a caixa', 'posicao', 'mudar a posicao', 'nao consigo mover', 'nao sai do lugar'],
    passos: [
      'Aperte o botão do mouse em cima da forma e, sem soltar, arraste.',
      'Solte onde quiser. Ela se ajeita sozinha na grade, e as setas vão junto.',
      'Se você estiver escrevendo nela, pegue pela beirada, fora das letras.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'tamanho',
    pergunta: 'Como aumentar ou diminuir uma forma?',
    termos: ['aumentar a forma', 'aumentar a caixa', 'diminuir a caixa', 'diminuir a forma', 'tamanho da caixa',
      'tamanho da forma', 'caixa maior', 'caixa menor', 'forma maior', 'forma menor', 'esticar', 'encolher', 'alargar',
      'redimensionar', 'mudar o tamanho', 'caixa muito grande', 'caixa muito pequena'],
    passos: [
      'Clique na forma. Aparecem quadradinhos azuis nos cantos.',
      'Aperte o mouse num quadradinho e arraste: para fora aumenta, para dentro diminui.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'forma-nova',
    pergunta: 'Como colocar uma forma nova?',
    termos: ['forma nova', 'nova forma', 'colocar forma', 'colocar outra forma', 'coloco outra forma', 'colocar caixa',
      'colocar outra caixa', 'colocar mais uma caixa', 'texto sem caixa', 'texto solto', 'texto sem borda', 'escrever fora da caixa', 'fazer um losango', 'fazer um circulo', 'fazer um quadrado', 'fazer uma caixa', 'adicionar', 'acrescentar', 'inserir', 'criar forma', 'criar caixa',
      'por um quadrado', 'colocar retangulo', 'colocar losango', 'colocar circulo', 'colocar bolinha',
      'colocar quadradinho'],
    passos: [
      'Olhe os botões da esquerda, em "Pôr na folha": Retângulo, Arredondado, Losango, Círculo e Texto.',
      'Clique no que quiser: a forma aparece na folha, pronta para escrever.',
      'Depois, arraste para o lugar certo.',
    ],
    mostrar: '.paleta',
    comum: true,
  },
  {
    id: 'ligar',
    pergunta: 'Como ligar uma forma na outra com seta?',
    termos: ['ligar', 'ligar as formas', 'ligar uma na outra', 'ligar as caixas', 'colocar seta', 'colocar a seta',
      'criar seta', 'faco a seta', 'faz a seta', 'fazer a seta', 'seta entre', 'colocar flecha', 'fazer flecha',
      'conectar', 'conectar as formas', 'conecto as formas', 'ligacao', 'apontar de uma pra outra', 'linha entre as caixas'],
    passos: [
      'Jeito mais fácil: clique numa forma e depois no + azul do lado onde quer a próxima. Ela nasce já ligada por seta.',
      'Para ligar duas formas que já existem: clique no botão Seta, à esquerda.',
      'Depois clique na forma de onde a seta SAI e, por último, na forma aonde ela CHEGA.',
    ],
    mostrar: '#bt-seta',
    comum: true,
  },
  {
    id: 'mais-azul',
    pergunta: 'Para que servem os + azuis em volta da forma?',
    termos: ['mais azul', 'os mais azuis', 'pra que serve o mais', 'para que serve o mais', 'bolinha azul',
      'bolinhas azuis', 'botao de mais', 'sinal de mais', 'circulo azul', 'simbolo de mais', 'botao azul'],
    passos: [
      'Eles aparecem quando você clica numa forma.',
      'Clicar num + cria outra forma igual daquele lado, já ligada por seta, pronta para escrever.',
      'Se não couber mais nada daquele lado, aparece um aviso.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'sim-nao',
    pergunta: 'Como colocar SIM ou NÃO na seta?',
    termos: ['sim e nao', 'sim ou nao', 'sim nao', 'sim na seta', 'nao na seta', 'escrever sim', 'escrever nao', 'escrevo sim', 'escrevo nao', 'escreve sim', 'escreve nao',
      'escrever sim na seta', 'colocar sim', 'colocar nao', 'por sim', 'por nao', 'escrever na seta', 'texto na seta',
      'nome na seta', 'palavra na seta', 'legenda da seta', 'rotulo', 'etiqueta'],
    passos: [
      'Clique em cima da seta. Ela fica azul.',
      'No painel da direita, clique em SIM ou em NÃO.',
      'Para outra palavra, escreva em "Ou escreva outro" e clique em Pôr.',
    ],
    mostrar: '#painel',
    comum: true,
  },
  {
    id: 'apagar-forma',
    pergunta: 'Como apagar uma forma?',
    termos: ['apagar a forma', 'apagar forma', 'apagar a caixa', 'apagar caixa', 'apago a caixa', 'apago uma caixa', 'apago a forma', 'apago uma forma', 'apagar o quadrado', 'apagar o losango',
      'apagar o circulo', 'apagar a bolinha', 'excluir', 'excluir a caixa', 'deletar', 'tirar a caixa', 'tirar a forma',
      'remover a caixa', 'remover', 'jogar fora', 'sumir com a caixa', 'eliminar'],
    passos: [
      'Clique na forma.',
      'Clique em Apagar, no painel da direita (ou aperte a tecla Delete).',
      'As setas ligadas a ela somem junto. Errou? Clique em Desfazer.',
    ],
    mostrar: '#painel',
    comum: true,
  },
  {
    id: 'apagar-seta',
    pergunta: 'Como apagar uma seta?',
    termos: ['apagar a seta', 'apagar seta', 'apagar a flecha', 'apagar flecha', 'tirar a seta', 'tirar a flecha',
      'excluir a seta', 'excluir a flecha', 'deletar a seta', 'remover a seta', 'remover a flecha', 'apagar a linha',
      'tirar a linha'],
    passos: [
      'Clique em cima da seta. Ela fica azul.',
      'Clique em "Apagar a seta", no painel da direita (ou aperte a tecla Delete).',
    ],
    mostrar: '#painel',
  },
  {
    id: 'desfazer',
    pergunta: 'Como desfazer o que eu fiz?',
    termos: ['desfazer', 'desfaco', 'desfaz', 'voltar', 'volta', 'volto', 'voltar atras', 'errei', 'fiz errado',
      'deu errado', 'estraguei', 'baguncei', 'ctrl z', 'como era antes', 'voltar como estava', 'cancelar o que fiz'],
    passos: [
      'Clique no botão Desfazer, no alto da tela (ou aperte Ctrl + Z).',
      'Cada clique volta um passo. Pode clicar várias vezes.',
      'Voltou demais? Clique em Refazer.',
    ],
    mostrar: '#bt-desfazer',
    comum: true,
  },
  {
    id: 'apagou-sem-querer',
    pergunta: 'Apaguei sem querer. Dá para recuperar?',
    termos: ['apaguei sem querer', 'sem querer', 'exclui sem querer', 'sumiu', 'sumiu a caixa', 'sumiu a forma',
      'desapareceu', 'perdi a forma', 'perdi a caixa', 'recuperar', 'trazer de volta', 'apaguei errado', 'apagou tudo'],
    passos: [
      'Clique em Desfazer, no alto da tela, quantas vezes precisar.',
      'Tudo volta, na ordem em que foi feito.',
    ],
    mostrar: '#bt-desfazer',
  },
  {
    id: 'refazer',
    pergunta: 'Para que serve o botão Refazer?',
    termos: ['refazer', 'refaz', 'ctrl y', 'desfiz demais', 'voltei demais', 'voltar o que desfiz', 'avancar'],
    passos: [
      'Ele desfaz o Desfazer: traz de volta o que você acabou de desfazer.',
      'Só funciona logo depois de usar o Desfazer.',
    ],
    mostrar: '#bt-refazer',
  },
  {
    id: 'cor',
    pergunta: 'Como mudar a cor de uma forma?',
    termos: ['cor', 'cores', 'mudar a cor', 'trocar a cor', 'pintar', 'colorir', 'colorido', 'cor da caixa',
      'cor da forma', 'fundo da caixa', 'vermelho', 'azul', 'verde', 'amarelo', 'laranja', 'rosa', 'roxo', 'cinza', 'branco'],
    passos: [
      'Clique na forma.',
      'No painel da direita, em "Cor", clique na cor que quiser.',
      'Para pintar várias de uma vez, escolha todas antes (veja "Como escolher várias formas de uma vez?").',
    ],
    mostrar: '#painel',
  },
  {
    id: 'borda',
    pergunta: 'Como deixar a borda tracejada (pontilhada)?',
    termos: ['tracejada', 'tracejado', 'pontilhada', 'pontilhado', 'borda', 'contorno', 'linha em volta',
      'risco em volta', 'tracinhos', 'borda lisa', 'linha da caixa pontilhada'],
    passos: [
      'Clique na forma.',
      'No painel da direita, em "Borda", clique em Tracejada. Para voltar, clique em Lisa.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'letra-tamanho',
    pergunta: 'Como aumentar ou diminuir a letra?',
    termos: ['letra maior', 'letra menor', 'aumentar a letra', 'diminuir a letra', 'tamanho da letra', 'letra pequena',
      'letra grande', 'letra muito pequena', 'fonte', 'fonte maior', 'fonte menor', 'aumentar a fonte', 'letra miuda',
      'nao consigo ler'],
    passos: [
      'Clique na forma.',
      'No painel da direita, em "Letra": A+ aumenta e A− diminui.',
      'Se o texto não couber, a forma cresce junto.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'negrito',
    pergunta: 'Como deixar a letra em negrito?',
    termos: ['negrito', 'letra forte', 'letra grossa', 'letra mais grossa', 'destacar', 'realcar', 'letra escura',
      'bold', 'grifar'],
    passos: [
      'Clique na forma.',
      'No painel da direita, clique em Negrito. Vale para todo o texto daquela forma.',
      'Clique de novo para tirar.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'alinhar',
    pergunta: 'Como deixar o texto à esquerda, em lista?',
    termos: ['alinhar', 'alinhamento', 'esquerda', 'texto na esquerda', 'centralizar', 'centralizado', 'no centro',
      'lista', 'fazer lista', 'topicos', 'itens', 'um embaixo do outro', 'organizar o texto', 'marcadores'],
    passos: [
      'Clique na forma.',
      'No painel da direita, em "Letra", clique em "À esquerda". Para voltar, "Centralizado".',
      'Para fazer lista, comece cada linha com um tracinho (-) e aperte Enter para ir para a próxima.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'pular-linha',
    pergunta: 'Como pular uma linha dentro da forma?',
    termos: ['pular linha', 'pular uma linha', 'nova linha', 'outra linha', 'linha de baixo', 'descer uma linha',
      'quebrar linha', 'enter', 'paragrafo'],
    passos: ['Enquanto escreve na forma, aperte a tecla Enter.'],
  },
  {
    id: 'trocar-forma',
    pergunta: 'Como trocar a forma (virar losango, círculo...)?',
    termos: ['trocar a forma', 'mudar a forma', 'trocar o formato', 'mudar o formato', 'virar losango', 'virar circulo',
      'virar quadrado', 'virar retangulo', 'transformar', 'mudar para losango', 'mudar pra losango',
      'mudar pra circulo', 'trocar quadrado por', 'mudar o desenho da caixa'],
    passos: [
      'Clique na forma.',
      'No painel da direita, em "Trocar a forma", clique no desenho da forma que quiser.',
      'O texto e a cor continuam.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'qual-forma',
    pergunta: 'Qual forma usar para cada coisa?',
    termos: ['qual forma usar', 'para que serve o losango', 'pra que serve o losango', 'o que e o losango',
      'serve o losango', 'serve o circulo', 'diferenca entre as formas', 'significado das formas', 'quando usar cada forma',
      'o que significa'],
    passos: [
      'Losango: uma pergunta de SIM ou NÃO. Dele costumam sair duas setas.',
      'Retângulo ou Arredondado: o que fazer, o passo, o lugar para onde a pessoa vai.',
      'Círculo: o começo ou o fim do fluxo.',
      'Texto: uma observação solta, sem caixa em volta.',
    ],
    mostrar: '.paleta',
  },
  {
    id: 'duplicar',
    pergunta: 'Como fazer uma cópia de uma forma?',
    termos: ['copiar', 'copia', 'duplicar', 'fazer uma copia', 'mais uma igual', 'outra igual', 'repetir a forma',
      'clonar', 'ctrl c', 'copiar e colar'],
    passos: [
      'Clique na forma.',
      'Clique em Duplicar, no painel da direita.',
      'A cópia aparece do lado, com a mesma cor e o mesmo tamanho. Arraste para onde quiser.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'varias',
    pergunta: 'Como escolher várias formas de uma vez?',
    termos: ['varias formas', 'varias caixas', 'selecionar varias', 'escolher varias', 'todas de uma vez', 'mover tudo',
      'mover varias', 'mover tudo junto', 'marcar varias', 'selecionar tudo', 'grupo', 'juntas', 'apagar varias',
      'pintar varias'],
    passos: [
      'Aperte o mouse num lugar vazio da folha e arraste, fazendo um retângulo em volta das formas.',
      'Ou segure a tecla Shift e clique em cada forma.',
      'Depois, dá para arrastar, pintar ou apagar todas juntas.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'seta-torta',
    pergunta: 'A seta ficou torta ou passando por cima. Como arrumar?',
    termos: ['seta torta', 'seta ficou torta', 'seta ta torta', 'seta dobrada', 'seta passando por cima', 'seta por cima',
      'seta feia', 'seta no lugar errado', 'arrumar a seta', 'endireitar a seta', 'flecha torta', 'seta cruzando',
      'seta atravessando', 'ajustar caminho', 'mudar o caminho da seta', 'seta reta', 'deixar a seta reta', 'mudar a seta de lugar', 'mover a seta'],
    passos: [
      'Arraste as formas para ficarem alinhadas, uma embaixo ou ao lado da outra: a seta fica reta sozinha.',
      'Ou clique na seta e, no painel da direita, em "Ajustar caminho", escolha por onde ela sai e por onde chega.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'inverter-seta',
    pergunta: 'A seta está apontando para o lado errado. Como virar?',
    termos: ['inverter', 'inverter a seta', 'seta ao contrario', 'seta invertida', 'apontando errado',
      'apontando pro lado errado', 'virar a seta', 'trocar a direcao', 'direcao da seta', 'sentido da seta',
      'ponta do outro lado'],
    passos: [
      'Clique na seta.',
      'Clique em "Inverter a seta", no painel da direita.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'titulo',
    pergunta: 'Como mudar o título?',
    termos: ['titulo', 'mudar o titulo', 'escrever o titulo', 'trocar o titulo', 'nome do fluxograma', 'trocar o nome',
      'cabecalho', 'faixa de cima', 'cor do titulo', 'cor da faixa', 'nome em cima'],
    passos: [
      'Clique no título, na faixa do alto da folha, e escreva. Enter termina.',
      'Para mudar a cor da faixa, clique no título e escolha a cor no painel da direita.',
    ],
    mostrar: '#titulo',
  },
  {
    id: 'deitar',
    pergunta: 'Como deixar a folha deitada (na horizontal)?',
    termos: ['deitar a folha', 'folha deitada', 'deitada', 'paisagem', 'horizontal', 'virar a folha', 'girar a folha',
      'folha em pe', 'em pe', 'retrato', 'vertical', 'folha de lado'],
    passos: [
      'Clique em "Deitar a folha", à esquerda, embaixo dos botões das formas.',
      'Para voltar, clique em "Pôr a folha em pé".',
      'Dica: o modelo foi feito com a folha em pé. Se deitar e ficar bagunçado, clique em Desfazer.',
    ],
    mostrar: '#bt-folha',
  },
  {
    id: 'imprimir',
    pergunta: 'Como imprimir?',
    termos: ['imprimir', 'imprimi', 'imprimo', 'impressora', 'impressao', 'tirar no papel', 'passar pro papel',
      'no papel', 'folha impressa'],
    passos: [
      'Clique em "Imprimir ou PDF", no alto da tela, e depois em Continuar.',
      'Na janela que abrir, escolha a impressora.',
      'Clique em Imprimir.',
    ],
    mostrar: '#bt-imprimir',
  },
  {
    id: 'pdf',
    pergunta: 'Como salvar em PDF?',
    termos: ['pdf', 'salvar em pdf', 'salvar pdf', 'gerar pdf', 'fazer pdf', 'arquivo pdf', 'transformar em pdf',
      'exportar', 'baixar pdf', 'imprimir em pdf'],
    passos: [
      'Clique em "Imprimir ou PDF", no alto da tela, e depois em Continuar.',
      'Na janela que abrir, em "Destino", escolha "Salvar como PDF".',
      'Clique em Salvar e escolha a pasta.',
    ],
    mostrar: '#bt-imprimir',
    comum: true,
  },
  {
    id: 'salvar',
    pergunta: 'Como salvar para continuar depois?',
    termos: ['salvar', 'salvo', 'guardar', 'gravar o trabalho', 'gravar o arquivo', 'continuar depois', 'nao perder', 'salvar o trabalho',
      'salva sozinho', 'salvar no computador', 'backup'],
    passos: [
      'Enquanto você trabalha, o sistema já guarda tudo sozinho neste computador.',
      'Para ter um arquivo (e levar para outro computador), clique em "Salvar no computador".',
      'O arquivo vai para a pasta Downloads, com o nome "Fluxograma - ...".',
    ],
    mostrar: '#bt-salvar',
    comum: true,
  },
  {
    id: 'abrir',
    pergunta: 'Como abrir um fluxograma que eu salvei?',
    termos: ['abrir', 'abrir o arquivo', 'abrir arquivo', 'carregar', 'continuar o que salvei', 'abrir o que salvei',
      'achar o arquivo', 'acho o arquivo', 'nao acho o arquivo', 'cade o arquivo', 'procurar o arquivo', 'onde fica o arquivo', 'onde esta o arquivo', 'arquivo salvo', 'arquivo json'],
    passos: [
      'Clique em Abrir, no alto da tela.',
      'Escolha o arquivo. Ele costuma estar na pasta Downloads, com o nome "Fluxograma - ...".',
      'Também dá para arrastar o arquivo para dentro da página.',
    ],
    mostrar: '#bt-abrir',
  },
  {
    id: 'outro-computador',
    pergunta: 'Como continuar em outro computador?',
    termos: ['outro computador', 'outro pc', 'outra maquina', 'levar para casa', 'levar pra casa', 'pen drive',
      'pendrive', 'trocar de computador', 'notebook', 'computador de casa'],
    passos: [
      'Neste computador, clique em "Salvar no computador".',
      'Leve o arquivo para o outro computador (pen drive, e-mail ou WhatsApp).',
      'No outro computador, abra este mesmo site e clique em Abrir.',
    ],
    mostrar: '#bt-salvar',
  },
  {
    id: 'perdi',
    pergunta: 'Fechei a página. Perdi o que fiz?',
    termos: ['perdi', 'perdi tudo', 'perdi o trabalho', 'fechei', 'fechei a pagina', 'fechou', 'fechar a pagina',
      'se eu fechar', 'sumiu tudo', 'desligou', 'acabou a luz', 'travou', 'atualizei a pagina', 'recarreguei',
      'vai perder'],
    passos: [
      'Não. Abrindo de novo neste mesmo computador e no mesmo navegador, está tudo lá.',
      'Só em outro computador (ou em outro navegador) é que não aparece. Para isso, use "Salvar no computador" e depois Abrir.',
    ],
  },
  {
    id: 'comecar-outro',
    pergunta: 'Como começar um fluxograma novo?',
    termos: ['comecar de novo', 'fluxograma novo', 'novo fluxograma', 'outro fluxograma', 'recomecar', 'do zero', 'zerar',
      'limpar tudo', 'folha nova', 'folha em branco', 'apagar tudo e comecar', 'comecar outro', 'apagar tudo', 'apaga tudo'],
    passos: [
      'Clique em "Começar outro", no alto da tela.',
      'O sistema pergunta se você quer salvar o atual antes.',
      'Depois escolha "Começar com o modelo" ou "Começar com a folha vazia".',
    ],
    mostrar: '#bt-novo',
  },
  {
    id: 'modelo',
    pergunta: 'O que é o modelo? Posso mudar ele?',
    termos: ['modelo', 'o modelo', 'mudar o modelo', 'formas prontas', 'esqueleto', 'modelo de curitiba', 'exemplo',
      'o que vem pronto', 'pode mudar o modelo'],
    passos: [
      'É um esqueleto com as formas já no lugar, todas em branco, parecido com o fluxo que a Regional mandou de exemplo.',
      'Pode escrever, mudar, apagar e acrescentar o que quiser. Nada ali é obrigatório.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'mandar',
    pergunta: 'Como mandar o fluxograma para a Regional?',
    termos: ['mandar', 'enviar', 'mandar para a regional', 'mandar pra regional', 'regional', 'email', 'whatsapp', 'zap',
      'compartilhar', 'anexar', 'entregar', 'mandar para a coordenadora', 'mandar por email', 'mandar por whatsapp'],
    passos: [
      'Para mandar pronto, para ler ou imprimir: salve em PDF ("Imprimir ou PDF") e mande o arquivo.',
      'Para alguém continuar mexendo: mande o arquivo de "Salvar no computador". A pessoa abre com o botão Abrir, neste site.',
    ],
    mostrar: '#bt-imprimir',
  },
  {
    id: 'forma-vermelha',
    pergunta: 'A forma ficou com um contorno vermelho. O que é?',
    termos: ['contorno vermelho', 'borda vermelha', 'vermelho em volta', 'ficou vermelho', 'passou da folha',
      'saiu da folha', 'fora da folha', 'cortado', 'vai sair cortado', 'margem', 'passou da margem'],
    passos: [
      'É um aviso: a forma passou da margem da folha e pode sair cortada na impressão.',
      'Diminua a letra (A−) ou alargue a forma, puxando o quadradinho do canto, para ela voltar para dentro.',
    ],
    mostrar: '#painel',
  },
  {
    id: 'texto-nao-cabe',
    pergunta: 'O texto não cabe na forma. E agora?',
    termos: ['nao cabe', 'texto nao cabe', 'nao coube', 'texto grande', 'muito texto', 'texto cortado', 'texto saindo',
      'texto escondido', 'texto espremido', 'texto passando', 'caixa pequena para o texto'],
    passos: [
      'A forma cresce sozinha para baixo quando o texto não cabe.',
      'Se ficar comprida demais, alargue a forma (puxe o quadradinho do canto) ou diminua a letra (A−).',
    ],
  },
  {
    id: 'forma-escondida',
    pergunta: 'Uma forma ficou escondida atrás de outra. Como pegar?',
    termos: ['escondida', 'atras da outra', 'atras de outra', 'ficou por baixo', 'embaixo da outra', 'uma em cima da outra',
      'sobreposta', 'em cima da outra', 'ficou em cima', 'encavalada', 'tampou', 'cobriu', 'sumiu atras'],
    passos: [
      'Clique na parte que aparece: enquanto escolhida, ela fica na frente das outras.',
      'Arraste para um lugar livre.',
      'Se não aparecer nada dela, arraste a forma de cima para o lado.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'grade',
    pergunta: 'O que são os quadradinhos cinza e a linha tracejada da folha?',
    termos: ['quadradinhos cinza', 'quadriculado', 'grade da folha', 'grade cinza', 'linhas cinza', 'fundo quadriculado',
      'linha tracejada da folha', 'pontilhado da folha', 'vai sair na impressao', 'quadrados no fundo'],
    passos: [
      'São guias para ajudar a alinhar as formas. Não saem na impressão.',
      'A linha tracejada é a margem: o que ficar dentro dela sai inteiro no papel.',
    ],
    mostrar: '#folha',
  },
  {
    id: 'celular',
    pergunta: 'Dá para usar no celular?',
    termos: ['celular', 'no celular', 'pelo celular', 'telefone', 'tablet', 'smartphone', 'tela pequena'],
    passos: [
      'Dá para abrir, ver e imprimir.',
      'Mas montar o fluxograma é bem mais fácil no computador, com mouse.',
    ],
  },
  {
    id: 'cancelar-seta',
    pergunta: 'Cliquei em Seta e quero desistir. Como cancelo?',
    termos: ['cancelar a seta', 'cancelar seta', 'cancelo a seta', 'desistir da seta', 'sair da seta', 'faixa amarela',
      'botao seta amarelo', 'travou na seta', 'nao sai da seta'],
    passos: ['Clique em Cancelar, na faixa amarela do alto (ou aperte a tecla Esc).'],
  },
];

// A lista que aparece com o campo vazio (e quando a busca não entende).
export const COMUNS = ['usar-geral', 'escrever', 'forma-nova', 'ligar', 'sim-nao', 'apagar-forma', 'desfazer', 'pdf', 'salvar'];
